# Generated by Django 5.2.4 on 2026-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_service_servicephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
                ('icon', models.CharField(blank=True, default='🛒', max_length=20, verbose_name='Иконка')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
