# Generated by Django 5.2.4 on 2026-06-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_moreservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreservices',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'More Service', 'verbose_name_plural': 'More services'},
        ),
    ]
