# Generated by Django 5.2.4 on 2026-06-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_moreservices_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='SliderService',
        ),
        migrations.RenameModel(
            old_name='ServicePhoto',
            new_name='SliderServicePhoto',
        ),
    ]
