# Generated by Django 5.2.4 on 2026-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_service_sliderservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
