# Generated by Django 5.2.4 on 2026-06-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_companyinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreservices',
            name='like',
            field=models.CharField(blank=True, default='🤍', max_length=20, verbose_name='Иконка'),
        ),
    ]
