# Generated by Django 5.2.4 on 2026-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_moreservices_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreservices',
            name='icon',
            field=models.ImageField(blank=True, default='🛒', max_length=20, upload_to='services/icons/', verbose_name='Иконка'),
        ),
    ]
